name: Custom Script Runner

on:
  push:
    branches:
      - main  # Runs when someone pushes to main branch

jobs:
  execute-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "👋 Hello from GitHub Actions!"

      - name: Show Directory
        run: pwd

      - name: List files
        run: ls -la
